// Presenter Mode walkthrough — content distilled from DEMO_GUIDE.md §§1, 4–9.
// Keep say-lines and expected numbers in sync with that document.
export type PresenterStep = {
	id: string;
	act: string;
	/** Hash-route tab to navigate to, or "" to stay put. */
	tab: string;
	/** data-presenter key of the on-screen element "Take me there" scrolls to and highlights. */
	target?: string;
	/** Also click the target (only for pure-UI navigation, e.g. opening the chat widget). */
	autoClick?: boolean;
	title: string;
	/** What to click / do on screen. */
	click: string;
	/** The exact line to say. */
	say: string;
	/** The number to expect on screen. */
	expect?: string;
	/** Terminal command to run (display only — presenter runs it). */
	terminal?: string;
};

export const PRESENTER_SCRIPT: PresenterStep[] = [
	{
		id: "act0-pitch",
		act: "Opening",
		tab: "operations",
		title: "The 30-second pitch",
		click: "Nothing yet — deliver the pitch before touching the screen.",
		say: "IIE is a process intelligence platform for the Office of the Head of Civil Service. It collects a unified event log from three source systems — RFID attendance, the leave workflow, and an HR chatbot — and automatically mines that log to discover how processes actually run: it draws the real process map, finds bottlenecks, flags cases that skip required approval steps, and turns all of that into decision-support recommendations for management.",
	},
	{
		id: "act1-system-map",
		act: "Act 1 — Operations",
		tab: "operations",
		target: "system-map",
		title: "System map",
		click: "Point at the system map at the top of the page.",
		say: "Every subsystem publishes events in one canonical format into a unified event log — that's the core design decision. New systems just start emitting events; nothing else changes.",
	},
	{
		id: "act1-stat-cards",
		act: "Act 1 — Operations",
		tab: "operations",
		target: "stat-cards",
		title: "Stat cards",
		click: "Point at the headline stat cards.",
		say: "These poll the API every 10 seconds — if an event arrives, the numbers move on their own.",
		expect: "150 employees",
	},
	{
		id: "act1-live-feed",
		act: "Act 1 — Operations",
		tab: "operations",
		target: "live-feed",
		title: "Live event feed + case trace",
		click: "Click any row in the live event feed — the case's chronological trace opens in a modal.",
		say: "This feed is pushed live over server-sent events — the moment any subsystem posts, it appears here. And every row is clickable: every case carries its complete audit trail.",
	},
	{
		id: "act1-heatmap",
		act: "Act 1 — Operations",
		tab: "operations",
		target: "heatmap",
		title: "Attendance heatmap",
		click: "Hover a red-tinted cell in the 30-day attendance heatmap to show its tooltip.",
		say: "Green intensity is clock-in volume; a red tint means more than 25% of staff were late that day. You can spot bad Mondays at a glance.",
	},
	{
		id: "act1-pipeline",
		act: "Act 1 — Operations",
		tab: "operations",
		target: "leave-pipeline",
		title: "Leave pipeline",
		click: "Point at the leave pipeline stage counts.",
		say: "This is the state machine working — every leave request moves through one of the two prescribed chains, and the pipeline shows where work is piling up.",
	},
	{
		id: "act2-process-map",
		act: "Act 2 — Process Intelligence",
		tab: "intelligence",
		target: "process-map",
		title: "The discovered process map",
		click: "Point at the nodes and edges of the process map; briefly switch the source to ATTENDANCE and CHATBOT, then back to LEAVE_WORKFLOW.",
		say: "Nobody drew this process map — the system discovered it from the event log. It found BOTH prescribed chains on its own: standard leave through F&A, study leave through RTDD. Nobody told it about the F&A/RTDD split — it read it out of the data. Red edges are transitions over their SLA threshold.",
	},
	{
		id: "act2-bottlenecks",
		act: "Act 2 — Process Intelligence",
		tab: "intelligence",
		target: "bottlenecks",
		title: "Bottleneck panel",
		click: "Read the top row of the Bottlenecks panel.",
		say: "The single slowest hand-off in the leave process is getting from the supervisor's desk to F&A verification — a median of over three days. That's a staffing or routing problem at one specific step, and the system localised it exactly.",
		expect: "supervisor_review → fa_verification · median 3.3d · P95 5.7d",
	},
	{
		id: "act2-variants",
		act: "Act 2 — Process Intelligence",
		tab: "intelligence",
		target: "variants",
		title: "Workflow variants",
		click: "Point at the workflow variants list.",
		say: "256 leave cases collapse into a handful of distinct paths — the full F&A chain, the full RTDD study chain, the rejection variants… and these, where supervisor review never happened.",
	},
	{
		id: "act2-conformance",
		act: "Act 2 — Process Intelligence",
		tab: "intelligence",
		target: "conformance",
		title: "Conformance panel",
		click: "Click a case id in the conformance panel — the full trace opens, showing the jump straight to verification.",
		say: "The conformance checker compares every case against the prescribed model for its leave type. In a real deployment this is the audit list — and every finding is inspectable down to the raw events.",
		expect: "22 skipped_step violations · ~91% conformant",
	},
	{
		id: "act3-banner",
		act: "Act 3 — Decision Support",
		tab: "decision",
		target: "insight-banner",
		title: "Top insight banner",
		click: "Point at the dark insight banner at the top.",
		say: "Mining results are for analysts. This page is for management — it turns the analysis into plain-English recommendations, ranked by severity.",
	},
	{
		id: "act3-departments",
		act: "Act 3 — Decision Support",
		tab: "decision",
		target: "dept-comparison",
		title: "Department comparison",
		click: "Point at Civil Service Council (late rate) and Public Relations Unit (leave cycle).",
		say: "Every unit, compared on two fixed scales — red marks anything more than 1.5× the office average. This is the kind of cross-directorate comparison OHCS currently can't produce without manual spreadsheets — here it's a by-product of the event log.",
		expect: "CSC 13.8% late · PR Unit 7.6-day leave cycle",
	},
	{
		id: "act3-recommendations",
		act: "Act 3 — Decision Support",
		tab: "decision",
		target: "recommendations",
		title: "Recommendation cards",
		click: "Scroll the recommendation cards.",
		say: "Bottleneck alerts, the conformance finding — 22 cases bypassed supervisor review, enforce routing at submission — and the variability note.",
	},
	{
		id: "act3-export",
		act: "Act 3 — Decision Support",
		tab: "decision",
		target: "export-buttons",
		title: "Export",
		click: "Point at the Download CSV and Print / Save as PDF buttons (top right).",
		say: "And this page leaves the building — the CSV drops the recommendations and department table straight into Excel, and Print produces a clean one-pager for a director's memo.",
	},
	{
		id: "act3-honesty",
		act: "Act 3 — Decision Support",
		tab: "decision",
		title: "Roadmap honesty",
		click: "Nothing — a verbal point.",
		say: "The recommendations are rule-generated today; an AI narrative layer over them is a planned next phase.",
	},
	{
		id: "act4-open",
		act: "Act 4 — AI Assistant",
		tab: "",
		target: "chat-pill",
		autoClick: true,
		title: "Open the assistant",
		click: "Click 'Ask OHCS assistant' (gradient pill, bottom-right). Show the 'Speaking as' dropdown and the suggestion chips.",
		say: "The assistant is retrieval-augmented: it embeds the actual OHCS policy documents into a vector database and answers strictly from retrieved excerpts — it can't invent policy. It also knows who it's talking to; per-user sign-in arrives with the SSO phase.",
	},
	{
		id: "act4-annual-leave",
		act: "Act 4 — AI Assistant",
		tab: "",
		target: "chat-input",
		title: "Policy question 1 — annual leave",
		click: "Ask: \"How many days of annual leave am I entitled to?\" — then point at the indigo source chips under the reply.",
		say: "The source chips are the proof it's RAG over the real policy documents, not memorised.",
		expect: "30 working days",
	},
	{
		id: "act4-grace",
		act: "Act 4 — AI Assistant",
		tab: "",
		target: "chat-input",
		title: "Policy question 2 — clock-in grace",
		click: "Ask: \"What is the grace period for morning clock-in?\"",
		say: "Straight from the attendance policy excerpt.",
		expect: "30 minutes — late after 8:30 a.m.",
	},
	{
		id: "act4-study-approver",
		act: "Act 4 — AI Assistant",
		tab: "",
		target: "chat-input",
		title: "Policy question 3 — study leave",
		click: "Ask: \"Who approves study leave applications?\"",
		say: "That's the Study Leave Policy we just saw in the process map — the chatbot and the miner agree because both read the same reality.",
		expect: "Director RTDD, after RTDD Schedule Officer review",
	},
	{
		id: "act4-personal",
		act: "Act 4 — AI Assistant",
		tab: "",
		target: "chat-input",
		title: "Personal data — no LLM",
		click: "Ask: \"How many days was I late this month?\"",
		say: "This is the hybrid design: personal data queries go straight to the database through deterministic rules — the language model only handles policy language.",
	},
	{
		id: "act4-transaction",
		act: "Act 4 — AI Assistant",
		tab: "",
		target: "chat-input",
		title: "Real transaction",
		click: "Say to the assistant: \"I'd like to request annual leave from 3 August 2026 to 7 August 2026.\" After it confirms, flip to the Operations tab — the new leave_submitted event is at the top of the live feed.",
		say: "The chatbot didn't just talk — it executed a real workflow transaction against the state machine, and you watched the event land in the log. Leave dates are only ever taken from the user's own message — the model can't invent dates for a transaction.",
		expect: "leave_submitted at top of live feed",
	},
	{
		id: "act5-submit",
		act: "Act 5 — My Leave",
		tab: "leave",
		target: "leave-submit",
		title: "Submit a request",
		click: "With 'Acting as' set to any officer, pick annual leave, choose dates, Submit.",
		say: "The chatbot is one front door to the leave process. This is the other — a self-service portal. Same state machine underneath.",
		expect: "Request appears under My requests · pending at supervisor review",
	},
	{
		id: "act5-approve-chain",
		act: "Act 5 — My Leave",
		tab: "leave",
		target: "approver-inbox",
		title: "Approve the full chain",
		click: "In the Approver inbox: approve at supervisor review (unit Assistant Director I), then F&A verification (F&A admin officer), then Director F&A approval. Then flip to Operations — the chain streamed through the live feed.",
		say: "The picker only offers officers whose role and unit allow them to act — the state machine would reject anyone else.",
		expect: "Request lands in completed",
	},
	{
		id: "act5-study-routing",
		act: "Act 5 — My Leave",
		tab: "leave",
		target: "leave-submit",
		title: "Study leave routes to RTDD",
		click: "Submit a study request, approve at supervisor review, and point at the inbox.",
		say: "Study leave doesn't go to F&A. It routes to RTDD — the Schedule Officer reviews, and only Director RTDD can approve. That's the real Civil Service rule, enforced by the same engine the miner audits against.",
	},
	{
		id: "act5-track",
		act: "Act 5 — My Leave",
		tab: "leave",
		target: "my-requests",
		title: "Track a request",
		click: "Expand a request under My requests — the step-by-step timeline with actor and timestamp.",
		say: "Every officer can see exactly where their request is and whose desk it's on.",
	},
	{
		id: "act6-validate",
		act: "Act 6 — Proof (optional)",
		tab: "",
		title: "Live validation",
		click: "Run the validation harness in a terminal.",
		say: "This measures the project's six PRD success metrics live, against the planted ground truth — the demo data deliberately plants these problems, and the harness measures detection against known answers.",
		expect: "6/6 metrics pass · conformance 22/22",
		terminal: "npm run validate",
	},
	{
		id: "act6-close",
		act: "Closing",
		tab: "",
		title: "One-minute recap",
		click: "Nothing — closing lines.",
		say: "One unified event log from every subsystem; automatic discovery of the real process — both leave chains, found by the miner itself; bottleneck and conformance analysis validated at 100% against known ground truth; management-ready recommendations, exportable to CSV and PDF; self-service leave that enforces the real approval rules; and an AI assistant that answers policy from the actual documents and executes real transactions. All on serverless infrastructure that deploys with a single command.",
	},
];
